### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by keshava15** [DagonMetric/ng-config-firebase-remote-config#51]
ERROR in ../node_modules/@dagonmetric/ng-config-firebase-remote-config/src/firebase-remote-config-provider.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get name(): string;
           ~~~~
../node_modules/@dagonmetric/ng-config/src/config.service.d.ts:30:9 - error TS1086: An accessor cannot be declared in an ambient context.

30     get providers(): ConfigProvider[];

**Comment by mmzliveid** [comment]
Could you please provide the following information?
1. Angular Version
2. Typescript version
3. 3. @dagonmetric/ng-config package version
4. @dagonmetric/ng-config-firebase-remote-config package version

You can also edit and test the in [stackblitz](https://stackblitz.com/github/dagonmetric/ng-config-firebase-remote-config/tree/master/samples/demo-app?file=src%2Fapp%2Fapp.module.ts)
